### PR TITLE
Refactoring Project, use pip install method

### PR DESCRIPTION
**Pull request by 1letter**
- remove unused buildout config files
- update .gitignore
- update .prettierrc
- update tox.ini
- update github workflow
- update setup.py, add requirements for tests
- update test setup, use WSGI_SERVER_FIXTURE
- add requirements for pip install method
- add sources.ini for mxdev

I need help to setup the correct github workflow for acceptance tests via robotframework. has anyone the know how?

### CODE REVIEW

**Comment by jensens** [comment]
> add sources.ini for mxdev

please name it `mx.ini` since meanwhile its more than sources, like version overrides.

**Comment by 1letter** [comment]
@petschki @thet @agitator 
i have now fixed the plone6 setup with pip installation. The robottests need some love ;-) many things are buggy, but this is hard work and need some time. first, i prefer to fix the issue #173, but i need some help. I didn't find out what could be the problem, perhaps a JS problem (async loading?). in a plone 5.2 setup with the same test_debug.robot Test, the results are fine. I would be happy, if anyone can guide me a little bit.

**Comment by 1letter** [comment]
Update:
If i disable ajaxLoad pattern option, then the behavior is like expected, no error.
`{'collectionfilter': '{"ajaxLoad": false}',`

**Comment by 1letter** [comment]
Update
I found the Bug. Missing `bind` in the Eventhandler. I will Update the Code.

**Comment by 1letter** [comment]
I think this piece of code did not the job.
```
self.$el.on(
  "collectionfilter:reload",
  function (e, data) {
    if (
      (data.noReloadSearch && this.$el.hasClass("collectionSearch")) ||
       (data.noReloadMap && this.$el.hasClass("collectionMaps"))
    ) {
      // don't reload search while typing or map while move/zooming
      return;
    }
    if (data.collectionUUID === this.options.collectionUUID) {
      self.reload(data.targetFilterURL);
    }
  }.bind(self)
);
I'm not sure, what the reason is. Maybe the new Base Pattern with the own local scope?
```

**Comment by 1letter** [comment]
Update, now i have a working local version :-) I will check in the update and continue work on the robot test

**Comment by petschki** [comment]
@1letter I picked up your work today. Thanks for starting this! I removed tox in favor of the mxdev Makefile and refactored the GHA matrix. Chromedriver is up and running, so next would be to fix the robot tests. I'll do some more fixes until 5pm today ...

**Comment by 1letter** [comment]
@petschki 
There is another PR with a commit which fix #173 https://github.com/collective/collective.collectionfilter/pull/176/commits/19763e888539cf288e55a5e5883e97de905b29fe
I will add this to this work.

**Review by 1letter — COMMENTED** [review]
`srcsetup.cfg` is empty and needed for what? can this file removed?

**Comment by petschki** [comment]
I don't know what `srcsetup.cfg` is for ... can be deleted imho.

The versions in package.json should be updated:

```
@plone/mockup=^5.0.0-beta.10
@patternslib/dev=^3.1.8
```

**Comment by 1letter** [comment]
> I don't know what `srcsetup.cfg` is for ... can be deleted imho.

if i run locally `VENV=on TEST_LAYER=AcceptanceTestingPortlet_AjaxEnabled ROBOT_BROWSER=firefox make test-layer-ignore-warnings` then the srcsetup.cfg is created. it should be append to .gitignore

**Comment by petschki** [comment]
hm ... interesting. there's only one test failure left, which I cannot reproduce locally https://github.com/collective/collective.collectionfilter/actions/runs/3910005398/jobs/6681703620

I'll give it a try on my ubuntu server, maybe its passing on MacOS and failing on Ubuntu with py3.11 ?

NOTE: for convenience I safe the robot_log files as artifacts for failed tests.

**Comment by petschki** [comment]
thats weird ... there's a traceback in the failing test saying that `context/@@main_template/macros/master` is not found? eh?

robot_test_sortingportlets_Scenario_Combine_sort_and_OR_filter_selenium-screenshot-1

**Review by petschki — APPROVED** [review]
👍🏼

**Comment by petschki** [comment]
ok... changing the runner to `ubuntu-20.04` fixes the tests. I will report that to the release team because there might be something wrong with Plone on Ubuntu 22.04 using python 3.11 

As this PR is now green I'll squash and merge it ... 🎉

**Comment by 1letter** [comment]
@petschki 
Thanks for this great work!

**Pull request merged**
