### PR TITLE
constrain selectable type of "Target Collection"

### LINKED ISSUE #43: selectable types in "target collection" should be collections only
this is commented right now. https://github.com/collective/collective.collectionfilter/blob/master/src/collective/collectionfilter/interfaces.py#L38 

should be activated again

### PR DESCRIPTION
**Pull request by petschki**
fixes #43

### CODE REVIEW

**Comment by petschki** [comment]
@thet any reason why this got commented?

**Comment by thet** [comment]
Yes - I use a different ``portal_type`` in a project. I'd rather have something like ``selectable_types_which_provide_interface = "plone.app.contenttypes.behaviors.collection.ISyndicatableCollection"``. But that's not possible.

**Comment by petschki** [comment]
ah, I see ... we could provide our own `vocabularyView` for the target_collection field which returns a catalog query on `object_provides="plone.app.contenttypes.behaviors.collection.ISyndicatableCollection"`

**Comment by petschki** [comment]
@thet I tried a bit with custom `CatalogSource` as a field vocabulary, but didn't get to a satisfying result with `RelatedItemsWidget`.... how about a registry configuration entry for the widget `selectableTypes` which defaults to `['Collection', ]` and could be overwritten by an integrator package (or TTW in the registry controlpanel) ...

**Pull request merged**
