### PR TITLE
[WIP] restore 5.0.x compatibility

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by thet** [comment]
@djay tnx for working on a plone 5.0 compatibility.

I don't want to merge that into master but use the 2.x branch for that.
That makes it way easier to develop new features, otherwise we'd always have to develop for 5.0 compatibility too. Also the last 5.0 compat approach broke things for 5.1.
Keeping the 2.x and master in sync should be easier than maintaining everything in the master branch.

Are you OK with that?

Any other opinions? @agitator @petschki

**Comment by djay** [comment]
@thet Having a fork makes it a lot harder to fix bugs in your code which is the problem we are facing now

**Comment by agitator** [comment]
I'm with @thet here and btw. shouldn't you get rid of py2.7 and update to 5.2 soonish? ;-)

**Comment by petschki** [comment]
@djay we use a branch in this repo and not a fork. This is a common method of keeping backward compatibility in many addons of plone.

@agitator nope ... python 2.7 will be there a long time after EOL ... at least until I've merged all my projects to py3 😋

**Comment by djay** [comment]
@petschki not everyone has rich clients willing to pay for the upgrade to an as yet unreleased plone version. Please be pragmatic. We are contributing to this work too. Have some consideration for your collaborators.

**Comment by djay** [comment]
@petschki @thet I think there is a good argument to merge this as it adds useful functionality: namely the ability for the themer or site admin to turn off AJAX loading if they choose. I can see it being problematic for some themes. The reason I like c.collectionfilter over eea.facetednavigation is because it's not making my theming effort harder and is a more default plone experience. Forcing AJAX loading as a compulsory thing I think is the wrong direction.
Other than turning off AJAX loading the changes needed are minimal. There are some enhancements to the relateditems widget we can't use in 5.0 but it's a progressive enhancement... it works ok without them and in fact by putting in a default this version is now better than master.

**Comment by petschki** [comment]
Overall this looks goot to me! Could you add an upgradestep from version 8->9 so that the lastcompiled-date gets updated in the registry? @thet I think then we could merge and release these improvements... what do you think?

**Comment by thet** [comment]
I agree. Thanks for your work and caring about this project @djay 
Can someone else take care of merging and releasing? I'm on vacation now.
@djay @petschki you both got maintainer access to the project on https://pypi.org/project/collective.collectionfilter/ , so make a release :)

**Comment by petschki** [comment]
done!

**Pull request merged**
