### PR TITLE
Fix intermittent robot test error with "leave site?" popup

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by djay** [comment]
Not sure if it depends on the time of day but it's done 3 runs now without failing. I think thats enough.

**Comment by petschki** [comment]
Are you sure the robot tests are running? The workflow file defines a 
```
if: failure()
```
for the robot parts.

**Review by petschki — CHANGES_REQUESTED** [review]
we should activate robot tests in github actions.

**Comment by djay** [comment]
@petschki 

yes they are running.
```
bin/test --all  --layer ${{ matrix.layer }}
```

The only steps that have if: failure() are outputting the  robot test report, not running the tests.

**Comment by djay** [comment]
@petschki you've made me realise we actually have the opposite problem. the current actions are only running the robot tests and not a unit tests. I'll fix that.

```
$ bin/test --list-tests  --all --layer Portlet_AjaxDisabled
Listing collective.collectionfilter.testing.CollectiveCollectionFilterLayer:AcceptanceTestingPortlet_AjaxDisabled tests:
  Scenario Sorting with result sorting portlet (test_sortingportlets.robot)
  Scenario Combine sort and OR filter (test_sortingportlets.robot)
  Scenario Add filter to collection (test_filterportlets.robot)
  Scenario Test Batching (test_filterportlets.robot)
  Scenario Hide when no options (test_filterportlets.robot)
  Scenario show hidden filter if just narrowed down (test_filterportlets.robot)
  Scenario dont hide hidden filter if just narrowed down (test_filterportlets.robot)
  Scenario Displaying multiple collection filters on a single page (test_filterportlets.robot)
  Scenario Combine search and AND filter (test_filterportlets.robot)
  Scenario Search filter (test_filterportlets.robot)
```

**Review by petschki — APPROVED** [review]
LGTM

**Pull request merged**
