### PR TITLE
Fix ajaxLoad of filters and listing

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@djay could you fix the tests regarding the new ajaxLoad pattern option? there was a bug, because this options was never read correctly and therefore the whole page never loaded ajax anymore ....

**Comment by petschki** [comment]
@nngu6036 this change breaks ajax reloading of filter items: https://github.com/collective/collective.collectionfilter/commit/2ddaf54f46da068495489069003c5528c2296ec6 ... if we revert that, everything works ok again ... are you able to fix that?

**Comment by petschki** [comment]
@nngu6036 FYI we've reverted the JS code and Plone 5.0 tests are passing with ajax loading ... if there's any problem for you in 5.0 please open a new PR

**Comment by djay** [comment]
Yes I think there is a problem. The tests should not be passing for 5.0. Will open a new PR. Probably it needs one test with ajax loading and one without.

**Comment by petschki** [comment]
@djay maybe together with fixing 5.0 tests here #72 ?

**Comment by djay** [comment]
You'll see a PR from us to solve https://github.com/collective/collective.collectionfilter/issues/79 first. That should solve the failure in #72. I think the current master will intermittently fail in the mean time.

**Pull request merged**
