### PR TITLE
show full catalog count on "all" option fixes #42

### LINKED ISSUE #42: Incorrect count on "all" when "Narrow down filter options" enabled and viewing a filtered result
This is known to affect branch 2.x on Plone 5.0.x

## How to replicate
Create a keyword portlet and ensure that "show count" and  "Narrow down filter options" is enabled.

### expected behaviour
The All count should not change as you click on keywords

### actual behaviour
The All count changes to match the count of the active query.

collectionfilter-al

### PR DESCRIPTION
**Pull request by pigeonflight**

### CODE REVIEW

**Comment by petschki** [comment]
I assume this is the same as #47 ? maybe you want to close it and keep this one open.

**Comment by pigeonflight** [comment]
@petschki I was assuming that the "All" count was always a result of removing all filtering. My assumptions were wrong.

My updated understanding is 
- "All" means "stop filtering on this facet" for the current result set (or `active query`). 
- "All" is always relative to the `active query` and the `facet` that it is presented on.

I think this is roughly saying what you said above in a different way. You expressed it in terms of constraints, I've expressed it in terms of changes to the active query.

I've included examples of **All-styled queries** below (mostly to help my thinking about the problem and maybe others reading this). 

## Filtering Scenarios
To keep it simple, I'm using a contrived collection that has the facets Title, Color and Type.
[
{Title:A,Color:[red,green],Type:Document},
{Title:B,Color:[blue],Type:Document},
{Title:C,Color:[red,yellow],Type:Document},
{Title:D,Color:[red,green],Type:News Item}
]

Let's look at two examples, one where the `active query` is for 'Red Documents' and the other where the `active query` is for 'Green Documents'
### Example 1 - Red Documents
active query: Color=red&Type=Document
active result:
[
{Title:A,Color:[red,green],Type:Document},
{Title:C,Color:[red,yellow],Type:Document},
]
active count: 2

#### All-styled queries
Stop filtering by Color: C̶o̶l̶o̶r̶=̶̶̶r̶̶̶e̶̶̶d̶̶̶&̶̶̶Type=Document
expected result:
[
{Title:A,Color:[red,green],Type:Document},
{Title:B,Color:[blue],Type:Document},
{Title:C,Color:[red,yellow],Type:Document},
]
expected count: 3

Stop filtering by Type: Type: Color=red&̶T̶y̶p̶e̶=̶D̶o̶c̶u̶m̶e̶n̶t̶
expected result:
[
{Title:A,Color:[red,green],Type:Document},
{Title:C,Color:[red,yellow],Type:Document},
{Title:D,Color:[red,green],Type:News Item}
]
expected count: 3

### Example 2 - Green Documents
active query: Color=green&Type=Document
active result:
[
{Title:A,Color:[red,green],Type:Document},
]
active count: 1

#### All-styled queries
Stop filtering by Color: C̶̶̶o̶̶̶l̶̶̶o̶̶̶r̶̶̶=̶̶̶̶̶̶̶g̶r̶e̶e̶n̶&̶̶̶̶̶̶̶Type=Document
expected result:
[
{Title:A,Color:[red,green],Type:Document},
{Title:B,Color:[blue],Type:Document},
{Title:C,Color:[red,yellow],Type:Document},
]
expected count: 3

Stop filtering by Type: Color=green&̶T̶y̶p̶e̶=̶D̶o̶c̶u̶m̶e̶n̶t̶

expected result:
[
{Title:A,Color:[red,green],Type:Document},
{Title:D,Color:[red,green],Type:News Item}
]
expected count: 2

I think this discussion is enough rubber duck debugging to give me clarity on the matter, look out for a fix to the pull request.

**Comment by petschki** [comment]
well ... thats how it exactly works right now. I do not see a bug right now. For example see our implementation here (sorry german content ...) https://www.weitererzaehlen.at/interviews/mediathek ... if you select one filter all other queries get narrowed down but the current selector keeps "all" as expected ... this is collectionfilter OOTB ...

**Comment by pigeonflight** [comment]
So there is no bug. However, I've done some further review. The behaviour that I'm experiencing is when "Narrow down filter options" is set on the collection filter portlet. Not sure why it would behave like that when "Narrow down filter options" is ticked.

narrowfilter

**Comment by pigeonflight** [comment]
Just noticed that you mentioned this the  "Narrow down filter options" issue on #42. I'm closing this request.

**Pull request closed without merging**
